class AppStrings {
  AppStrings._();

  static const Map<String, String> _th = {
    'password_max_length': 'รหัสผ่านยาวเกิน 128 ตัวอักษร กรุณาใช้รหัสที่สั้นลง',
    'password_lowercase': 'ตัวพิมพ์เล็ก a–z อย่างน้อย 1 ตัว',
    'password_uppercase': 'ตัวพิมพ์ใหญ่ A–Z อย่างน้อย 1 ตัว',
    'password_digit': 'ตัวเลข 0–9 อย่างน้อย 1 ตัว',
    'password_symbol': 'สัญลักษณ์ เช่น ! @ # อย่างน้อย 1 ตัว',
    'password_common': 'รหัสผ่านนี้เดาง่าย กรุณาเลือกวลีอื่นที่ไม่ซ้ำกับบัญชีอื่น',
    'password_valid': 'รหัสผ่านผ่านเงื่อนไขแล้ว',
    'password_confirmed': 'รหัสผ่านตรงกันแล้ว',

    'edit': 'แก้ไข',
    'delete': 'ลบ',
    'all': 'ทั้งหมด',
    'no_income_data': 'ยังไม่มีข้อมูลรายรับ',
    'edit_goal': 'แก้ไขเป้าหมาย',
    'pin_goal': 'ปักหมุดบนหน้าแรก',
    'unpin_goal': 'เลิกปักหมุด',
    'manage_goal': 'จัดการเป้าหมาย',
    'delete_goal_confirm': 'ลบเป้าหมายนี้หรือไม่?',
    'delete_goal_notice': 'ลบเฉพาะเป้าหมาย ประวัติการโอนเงินเดิมยังอยู่และยอดกระเป๋าเงินไม่เปลี่ยน',
    'enter_confirm_password': 'กรุณากรอกยืนยันรหัสผ่าน',
    'password_requirements': 'ใช้ 6 ตัวอักษรขึ้นไป และครบทุกเงื่อนไขด้านล่าง',
    'target_below_saved': 'ยอดเป้าหมายต้องไม่น้อยกว่าเงินที่ออมแล้ว',

    // ---------------- Bottom Nav ----------------
    'nav_home': 'หน้าหลัก',
    'nav_wallet': 'กระเป๋าเงิน',
    'nav_add': 'เพิ่มรายการ',
    'nav_stat': 'สถิติ',
    'nav_menu': 'เมนู',

    // ---------------- Home ----------------
    'greeting': 'สวัสดี',
    'default_user': 'ผู้ใช้งาน',
    'total_income': 'รายรับรวม',
    'total_expense': 'รายจ่ายรวม',
    'net_balance': 'คงเหลือสุทธิ',
    'total_expenses_6m': 'Total Expenses (6 เดือนล่าสุด)',
    'exchange_rate': 'อัตราแลกเปลี่ยน',
    'buy': 'ซื้อ',
    'sell': 'ขาย',

    // ---------------- History ----------------
    'history': 'ประวัติ',
    'filter_all': 'ทั้งหมด',
    'filter_daily': 'รายวัน',
    'no_transactions': 'ยังไม่มีรายการ',
    'no_expense_data': 'ยังไม่มีข้อมูลรายจ่าย',
    'today': 'วันนี้',
    'yesterday': 'เมื่อวาน',

    // ---------------- Wallet ----------------
    'wallet_title': 'กระเป๋าเงิน',
    'wallet_header': 'กระเป๋าเงิน BUDGETMATE',
    'total_balance': 'ยอดคงเหลือรวม',
    'income_expense': 'รายรับ-รายจ่าย',
    'income': 'รายรับ',
    'expense': 'รายจ่าย',
    'goal_saving': 'เป้าหมายการออม',
    'goals_in_progress': 'เป้าหมายที่กำลังดำเนินการ',

    // ---------------- Income/Expense Add ----------------
    'back_home': 'กลับหน้าหลัก',
    'incomes_tab': 'รายรับ',
    'expenses_tab': 'รายจ่าย',
    'save': 'บันทึก',
    'categories': 'หมวดหมู่',
    'note_optional': 'หมายเหตุ (ไม่บังคับ)',
    'items_added': 'จำนวนรายการที่เพิ่ม',
    'tap_to_edit': '(แตะเพื่อแก้ไข)',
    'editing': 'กำลังแก้ไข',
    'cancel_edit': 'ยกเลิก',
    'select_category_prompt': 'เลือกหมวดหมู่ด้านบน แล้วกรอกจำนวนเงิน',
    'selected_category': 'หมวดหมู่ที่เลือก',
    'no_categories_for_type': 'ยังไม่มีหมวดหมู่สำหรับประเภทนี้',
    'showing_categories': 'แสดงรายการทั้งหมด',
    'items_unit': 'รายการ',
    'enter_amount': 'กรุณาระบุจำนวนเงิน',
    'select_category': 'กรุณาเลือกหมวดหมู่',
    'add_at_least_one': 'กรุณาเพิ่มรายการอย่างน้อย 1 รายการ',
    'save_failed': 'บันทึกไม่สำเร็จ',

    // ---------------- Goal Saving ----------------
    'ledger_balance': 'ยอดคงเหลือ\nBUDGETMATE',
    'no_goals': 'ยังไม่มีเป้าหมายการออม',
    'deposit_title': 'เติมเงินเข้าเป้าหมาย',
    'ledger_remaining': 'Ledger คงเหลือ',
    'needed_more': 'ต้องการอีก',
    'quarter': '25%',
    'half': '50%',
    'full_remaining': 'เต็มจำนวนที่ขาด',
    'insufficient_balance': 'Ledger Balance ไม่พอสำหรับโอนเข้าเป้าหมายนี้',
    'cancel': 'ยกเลิก',
    'transfer': 'โอนเงิน',
    'enter_valid_amount': 'กรุณากรอกจำนวนเงินให้ถูกต้อง',

    // ---------------- Add Goal Saving ----------------
    'goal_name_hint': 'ชื่อเป้าหมาย',
    'target_date_label': 'วันที่ต้องการให้ถึงเป้าหมาย',
    'fill_name_and_amount': 'กรุณากรอกชื่อและจำนวนเงินเป้าหมาย',

    // ---------------- Statistic ----------------
    'statistic_title': 'สถิติ',
    'most_spent_category': 'หมวดหมู่ที่ใช้จ่ายมากที่สุด',
    'near_target': 'ใกล้ถึงเป้าหมายแล้ว!',

    // ---------------- Period Filter (Home / Statistic) ----------------
    'expense_trend': 'แนวโน้มรายจ่าย',
    'period_day': 'วัน',
    'period_month': 'เดือน',
    'period_year': 'ปี',

    // ---------------- Account Setting ----------------
    'account_setting_title': 'ตั้งค่าบัญชี',
    'account_section': 'บัญชี',
    'manage_profile': 'จัดการโปรไฟล์',
    'password_security': 'รหัสผ่านและความปลอดภัย',
    'language': 'ภาษา',
    'preferences_section': 'การตั้งค่า',
    'about_us': 'เกี่ยวกับเรา',
    'theme': 'ธีม',
    'theme_dark': 'มืด',
    'theme_light': 'สว่าง',
    'transaction_saved': 'บันทึกรายการสำเร็จ',
    'goal_saved': 'บันทึกเป้าหมายสำเร็จ',
    'goal_updated': 'แก้ไขเป้าหมายสำเร็จ',
    'transaction_updated': 'แก้ไขรายการสำเร็จ',
    'transaction_duplicated': 'ทำสำเนารายการสำเร็จ',
    'transaction_deleted': 'ลบรายการสำเร็จ',
    'success_notes': 'แจ้งเตือนเมื่อทำรายการสำเร็จ',
    'dismiss_success_notice': 'ปิดข้อความแจ้งเตือน',
    'enabled': 'เปิดใช้งาน',
    'disabled': 'ปิดใช้งาน',
    'logout': 'ออกจากระบบ',

    // ---------------- Default category names (by category id) ----------------
    'cat_c01': 'อาหาร',
    'cat_c02': 'เครื่องดื่ม',
    'cat_c03': 'ที่พัก',
    'cat_c04': 'ยานพาหนะ',
    'cat_c05': 'ภาษี',
    'cat_c06': 'ช้อปปิ้ง',
    'cat_c07': 'ของขวัญ',
    'cat_c08': 'ท่องเที่ยว',
    'cat_c09': 'ความงาม',
    'cat_c10': 'บันเทิง',
    'cat_c11': 'กีฬา',
    'cat_c12': 'สัตว์เลี้ยง',
    'cat_c13': 'การศึกษา',
    'cat_c14': 'เงินเดือน',
    'cat_c15': 'รายได้เสริม',
    'cat_c16': 'โบนัส',
    'cat_c17': 'เงินออม',

    // ---------------- Custom category (Other) ----------------
    'other_category': 'อื่นๆ',
    'add_custom_category_title': 'เพิ่มหมวดหมู่ใหม่',
    'category_name_hint': 'ชื่อหมวดหมู่',
    'please_enter_category_name': 'กรุณากรอกชื่อหมวดหมู่',
    'choose_icon': 'เลือกไอคอน',
    'add': 'เพิ่ม',
    'edit_username': 'แก้ไขชื่อผู้ใช้',
    'display_name': 'ชื่อที่แสดง',
    'username_hint': 'ชื่อผู้ใช้',
    'enter_username': 'กรุณากรอกชื่อผู้ใช้',
    'save_action': 'บันทึก',
    'choose_language': 'เลือกภาษา',
    'about_title': 'เกี่ยวกับ BUDGETMATE',
    'about_body':
        'BUDGETMATE คือแอปช่วยจัดการรายรับ-รายจ่ายและเป้าหมายการออมเงินส่วนตัว '
            'พัฒนาโดยนิสิตคณะวิศวกรรมศาสตร์ มหาวิทยาลัยเกษตรศาสตร์\n\nเวอร์ชัน 1.0.0',
    'close': 'ปิด',
    'take_photo': 'ถ่ายรูปใหม่',
    'choose_from_gallery': 'เลือกจากคลังภาพ',
    'remove_photo': 'ลบรูปโปรไฟล์',

    // ---------------- Change Password ----------------
    'current_password': 'รหัสผ่านเดิม',
    'current_password_hint': 'กรอกรหัสผ่านปัจจุบัน',
    'new_password': 'รหัสผ่านใหม่',
    'new_password_hint': 'อย่างน้อย 6 ตัวอักษร',
    'confirm_new_password': 'ยืนยันรหัสผ่านใหม่',
    'confirm_new_password_hint': 'กรอกรหัสผ่านใหม่อีกครั้ง',
    'enter_current_password': 'กรุณากรอกรหัสผ่านเดิม',
    'password_min_length': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    'password_mismatch': 'รหัสผ่านใหม่ไม่ตรงกัน',
    'change_password_success': 'เปลี่ยนรหัสผ่านสำเร็จ',
    'save_new_password': 'บันทึกรหัสผ่านใหม่',

    // ---------------- Forgot Password ----------------
    'forgot_password_title': 'ลืมรหัสผ่าน',
    'reset_password_heading': 'รีเซ็ตรหัสผ่าน',
    'reset_password_desc':
        'กรอกอีเมลที่ใช้สมัครสมาชิก ระบบจะส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ไปให้ทางอีเมล',
    'email': 'อีเมล',
    'enter_email': 'กรุณากรอกอีเมล',
    'enter_new_password': 'กรุณากรอกรหัสผ่านใหม่',
    'password_not_match': 'รหัสผ่านไม่ตรงกัน',
    'reset_success': 'ตั้งรหัสผ่านใหม่สำเร็จ กรุณาเข้าสู่ระบบด้วยรหัสผ่านใหม่',
    'reset_email_sent':
        'ส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ไปยังอีเมลของคุณแล้ว กรุณาตรวจสอบกล่องจดหมาย',
    'back_to_login': 'กลับไปหน้าเข้าสู่ระบบ',

    // ---------------- Login ----------------
    'app_name': 'BUDGETMATE',
    'login_subtitle': 'เข้าสู่ระบบเพื่อจัดการเงินของคุณ',
    'login': 'เข้าสู่ระบบ',
    'register': 'สมัครสมาชิก',
    'email_hint': 'อีเมล',
    'password_hint': 'รหัสผ่าน',
    'sign_in': 'เข้าสู่ระบบ',
    'forgot_password_q': 'ลืมรหัสผ่าน?',
    'login_error': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',

    // ---------------- Register ----------------
    'create_account': 'สร้างบัญชีใหม่',
    'register_subtitle': 'เริ่มจัดการเงินของคุณกับ BUDGETMATE',
    'name_hint': 'ชื่อ',
    'confirm_password_hint': 'ยืนยันรหัสผ่าน',
    'sign_up': 'สมัครสมาชิก',
    'already_have_account': 'มีบัญชีอยู่แล้ว? ',
    'fill_all_fields': 'กรุณากรอกข้อมูลให้ครบถ้วน',
    'email_in_use': 'อีเมลนี้ถูกใช้งานแล้ว',

    // ---------------- Language Setup ----------------
    'setup_title': 'ตั้งค่าเริ่มต้น',
    'setup_desc': 'เลือกภาษาและสกุลเงินที่คุณต้องการใช้',
    'language_label': 'ภาษา',
    'currency_label': 'สกุลเงิน',
    'next': 'ถัดไป',

    // ---------------- Splash / Loading ----------------
    'splash_tagline': 'จัดการเงินของคุณให้เป็นเรื่องง่าย',

    // ---------------- DataService error messages ----------------
    'please_login_first': 'กรุณาเข้าสู่ระบบก่อน',
    'account_not_found': 'ไม่พบบัญชีที่ใช้อีเมลนี้ในระบบ',
    'wrong_current_password': 'รหัสผ่านเดิมไม่ถูกต้อง',
    'goal_not_found': 'ไม่พบเป้าหมายนี้',
    'transfer_failed': 'เกิดข้อผิดพลาด ไม่สามารถโอนเงินได้ กรุณาลองใหม่อีกครั้ง',
    'insufficient_ledger_prefix': 'ยอดเงินคงเหลือใน Ledger ไม่เพียงพอ (คงเหลือ',
    'amount_exceeds_prefix': 'จำนวนเงินเกินยอดที่ต้องการอีก (ต้องการอีก',
  };

  static const Map<String, String> _en = {
    'password_max_length': 'Password exceeds the 128-character limit. Choose a shorter password.',
    'password_lowercase': 'At least 1 lowercase letter (a–z)',
    'password_uppercase': 'At least 1 uppercase letter (A–Z)',
    'password_digit': 'At least 1 number (0–9)',
    'password_symbol': 'At least 1 symbol, such as ! @ #',
    'password_common': 'This password is too common. Choose a different, unique passphrase.',
    'password_valid': 'Password meets the requirements',
    'password_confirmed': 'Passwords match',

    'edit': 'Edit',
    'delete': 'Delete',
    'all': 'All',
    'no_income_data': 'No income data',
    'edit_goal': 'Edit goal',
    'pin_goal': 'Pin to home',
    'unpin_goal': 'Unpin from home',
    'manage_goal': 'Manage goal',
    'delete_goal_confirm': 'Delete this goal?',
    'delete_goal_notice': 'Only the goal is deleted. Past transfers and your wallet balance stay unchanged.',
    'enter_confirm_password': 'Please confirm your password',
    'password_requirements': 'Use at least 6 characters and meet each requirement below',
    'target_below_saved': 'Target cannot be less than current savings',

    'nav_home': 'Home',
    'nav_wallet': 'Wallet',
    'nav_add': 'Add',
    'nav_stat': 'Stats',
    'nav_menu': 'Menu',

    'greeting': 'Hello',
    'default_user': 'User',
    'total_income': 'Total Income',
    'total_expense': 'Total Expense',
    'net_balance': 'Net Balance',
    'total_expenses_6m': 'Total Expenses (Last 6 Months)',
    'exchange_rate': 'Exchange Rate',
    'buy': 'Buy',
    'sell': 'Sell',

    'history': 'History',
    'filter_all': 'All',
    'filter_daily': 'Daily',
    'no_transactions': 'No transactions yet',
    'no_expense_data': 'No expense data yet',
    'today': 'TODAY',
    'yesterday': 'YESTERDAY',

    'wallet_title': 'Wallet',
    'wallet_header': 'BUDGETMATE WALLET',
    'total_balance': 'Total Balance',
    'income_expense': 'Income/Expense',
    'income': 'Income',
    'expense': 'Expense',
    'goal_saving': 'Goal Saving',
    'goals_in_progress': 'goals in progress',

    'back_home': 'Back to Home',
    'incomes_tab': 'Incomes',
    'expenses_tab': 'Expenses',
    'save': 'SAVE',
    'categories': 'Categories',
    'note_optional': 'Note (optional)',
    'items_added': 'Items added',
    'tap_to_edit': '(tap to edit)',
    'editing': 'Editing',
    'cancel_edit': 'Cancel',
    'select_category_prompt': 'Select a category above, then enter the amount',
    'selected_category': 'Selected category',
    'no_categories_for_type': 'No categories for this type yet',
    'showing_categories': 'Showing all',
    'items_unit': 'items',
    'enter_amount': 'Please enter an amount',
    'select_category': 'Please select a category',
    'add_at_least_one': 'Please add at least one item',
    'save_failed': 'Save failed',

    'ledger_balance': 'BUDGETMATE\nLedger Balance',
    'no_goals': 'No savings goals yet',
    'deposit_title': 'Deposit to goal',
    'ledger_remaining': 'Ledger balance',
    'needed_more': 'Needed',
    'quarter': '25%',
    'half': '50%',
    'full_remaining': 'Full remaining',
    'insufficient_balance': 'Ledger balance is insufficient to transfer to this goal',
    'cancel': 'Cancel',
    'transfer': 'Transfer',
    'enter_valid_amount': 'Please enter a valid amount',

    'goal_name_hint': 'Goal name',
    'target_date_label': 'Target date',
    'fill_name_and_amount': 'Please enter goal name and target amount',

    'statistic_title': 'Statistic',
    'most_spent_category': 'Most spent category',
    'near_target': 'Almost there!',

    // ---------------- Period Filter (Home / Statistic) ----------------
    'expense_trend': 'Expense Trend',
    'period_day': 'Day',
    'period_month': 'Month',
    'period_year': 'Year',

    'account_setting_title': 'Account Setting',
    'account_section': 'Account',
    'manage_profile': 'Manage Profile',
    'password_security': 'Password & Security',
    'language': 'Language',
    'preferences_section': 'Preferences',
    'about_us': 'About Us',
    'theme': 'Theme',
    'theme_dark': 'Dark',
    'theme_light': 'Light',
    'transaction_saved': 'Transaction saved successfully',
    'goal_saved': 'Goal saved successfully',
    'goal_updated': 'Goal updated successfully',
    'transaction_updated': 'Transaction updated successfully',
    'transaction_duplicated': 'Transaction duplicated successfully',
    'transaction_deleted': 'Transaction deleted successfully',
    'success_notes': 'Success Notes',
    'dismiss_success_notice': 'Dismiss notification',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'logout': 'Log out',

    // ---------------- Default category names (by category id) ----------------
    'cat_c01': 'Food',
    'cat_c02': 'Drinks',
    'cat_c03': 'Housing',
    'cat_c04': 'Transport',
    'cat_c05': 'Tax',
    'cat_c06': 'Shopping',
    'cat_c07': 'Gifts',
    'cat_c08': 'Travel',
    'cat_c09': 'Beauty',
    'cat_c10': 'Entertainment',
    'cat_c11': 'Sports',
    'cat_c12': 'Pets',
    'cat_c13': 'Education',
    'cat_c14': 'Salary',
    'cat_c15': 'Side Income',
    'cat_c16': 'Bonus',
    'cat_c17': 'Savings',

    // ---------------- Custom category (Other) ----------------
    'other_category': 'Other',
    'add_custom_category_title': 'Add new category',
    'category_name_hint': 'Category name',
    'please_enter_category_name': 'Please enter a category name',
    'choose_icon': 'Choose icon',
    'add': 'Add',
    'edit_username': 'Edit username',
    'display_name': 'Display name',
    'username_hint': 'Username',
    'enter_username': 'Please enter a username',
    'save_action': 'Save',
    'choose_language': 'Choose language',
    'about_title': 'About BUDGETMATE',
    'about_body':
        'BUDGETMATE is an app that helps you manage income, expenses, and personal savings goals. '
            'Developed by engineering students at Kasetsart University.\n\nVersion 1.0.0',
    'close': 'Close',
    'take_photo': 'Take a new photo',
    'choose_from_gallery': 'Choose from gallery',
    'remove_photo': 'Remove photo',

    'current_password': 'Current password',
    'current_password_hint': 'Enter current password',
    'new_password': 'New password',
    'new_password_hint': 'At least 6 characters',
    'confirm_new_password': 'Confirm new password',
    'confirm_new_password_hint': 'Re-enter new password',
    'enter_current_password': 'Please enter your current password',
    'password_min_length': 'Password must be at least 6 characters',
    'password_mismatch': 'New passwords do not match',
    'change_password_success': 'Password changed successfully',
    'save_new_password': 'Save new password',

    'forgot_password_title': 'Forgot Password',
    'reset_password_heading': 'Reset password',
    'reset_password_desc':
        'Enter the email you registered with and we will send you a link to set a new password',
    'email': 'Email',
    'enter_email': 'Please enter your email',
    'enter_new_password': 'Please enter a new password',
    'password_not_match': 'Passwords do not match',
    'reset_success': 'Password reset successful, please log in with your new password',
    'reset_email_sent': 'We\'ve sent a password reset link to your email. Please check your inbox.',
    'back_to_login': 'Back to login',

    'app_name': 'BUDGETMATE',
    'login_subtitle': 'Log in to manage your money',
    'login': 'Login',
    'register': 'Register',
    'email_hint': 'Email',
    'password_hint': 'Password',
    'sign_in': 'Sign In',
    'forgot_password_q': 'Forgot password?',
    'login_error': 'Invalid email or password',

    'create_account': 'Create a new account',
    'register_subtitle': 'Start managing your money with BUDGETMATE',
    'name_hint': 'Name',
    'confirm_password_hint': 'Confirm Password',
    'sign_up': 'Sign Up',
    'already_have_account': 'Already have an account? ',
    'fill_all_fields': 'Please fill in all fields',
    'email_in_use': 'This email is already in use',

    'setup_title': 'Initial Setup',
    'setup_desc': 'Choose your preferred language and currency',
    'language_label': 'Language',
    'currency_label': 'Currency',
    'next': 'Next',

    'splash_tagline': 'Managing your money made easy',

    // ---------------- DataService error messages ----------------
    'please_login_first': 'Please log in first',
    'account_not_found': 'No account found with this email',
    'wrong_current_password': 'Current password is incorrect',
    'goal_not_found': 'Goal not found',
    'transfer_failed': 'Something went wrong. Could not transfer. Please try again.',
    'insufficient_ledger_prefix': 'Insufficient ledger balance (balance',
    'amount_exceeds_prefix': 'Amount exceeds what is still needed (needed',
  };

  static Map<String, String> of(String? language) =>
      language == 'English' ? _en : _th;
}
