// Generated by scripts/generate_password_policy.py. Edit config/password_policy.json.
const passwordMinLength = 6;
const passwordMaxLength = 128;
const _blockedPasswords = <String>{
  "123456789012345",
  "1234567890123456",
  "12345678901234567890",
  "passwordpassword",
  "password123456789",
  "password12345678",
  "qwertyuiopasdfgh",
  "qwertyuiopasdfghjkl",
  "qwerty1234567890",
  "aaaaaaaaaaaaaaa",
  "111111111111111",
  "000000000000000",
  "budgetmate123456",
  "budgetmatepassword",
  "budgetmatebudgetmate"
};

/// New passwords only. Never trim, truncate or rewrite a user's secret.
/// Minimum counts Unicode code points; maximum uses Firebase-compatible UTF-16 units.
String? passwordValidationKey(String password) {
  if (password.runes.length < passwordMinLength) return 'password_min_length';
  if (password.length > passwordMaxLength) return 'password_max_length';
  if (password.trim().isEmpty || _blockedPasswords.contains(password.toLowerCase())) {
    return 'password_common';
  }
  if (!RegExp("[a-z]").hasMatch(password)) return 'password_lowercase';
  if (!RegExp("[A-Z]").hasMatch(password)) return 'password_uppercase';
  if (!RegExp("[0-9]").hasMatch(password)) return 'password_digit';
  if (!RegExp("[\\x21-\\x2F\\x3A-\\x40\\x5B-\\x60\\x7B-\\x7E]").hasMatch(password)) return 'password_symbol';
  return null;
}
