import 'package:flutter/material.dart';

/// Icons persisted by categories and savings goals. Keep legacy entries when
/// changing the picker so existing records still render after an app update.
/// Constant references allow release builds to tree-shake the icon font.
const persistedIcons = <IconData>[
  Icons.apartment,
  Icons.camera_alt,
  Icons.card_giftcard,
  Icons.card_membership,
  Icons.category_outlined,
  Icons.checkroom,
  Icons.commute,
  Icons.copyright,
  Icons.currency_bitcoin,
  Icons.directions_car,
  Icons.edit_note,
  Icons.emoji_events,
  Icons.family_restroom,
  Icons.fitness_center,
  Icons.flight,
  Icons.handshake,
  Icons.health_and_safety,
  Icons.home,
  Icons.home_work,
  Icons.insights,
  Icons.lightbulb,
  Icons.local_cafe,
  Icons.local_gas_station,
  Icons.local_hospital,
  Icons.local_movies,
  Icons.local_parking,
  Icons.local_taxi,
  Icons.medication,
  Icons.music_note,
  Icons.payments,
  Icons.people_alt,
  Icons.pets,
  Icons.receipt_long,
  Icons.request_quote,
  Icons.restaurant,
  Icons.savings,
  Icons.school,
  Icons.sell,
  Icons.shopping_bag,
  Icons.shopping_cart,
  Icons.smartphone,
  Icons.spa,
  Icons.sports_esports,
  Icons.sports_soccer,
  Icons.star_rounded,
  Icons.storefront,
  Icons.subscriptions,
  Icons.support,
  Icons.trending_up,
  Icons.volunteer_activism,
  Icons.water_drop,
  Icons.wifi,
];

IconData persistedIconFromCodePoint(int codePoint) => persistedIcons.firstWhere(
      (icon) => icon.codePoint == codePoint,
      orElse: () => Icons.category_outlined,
    );
