// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0JWDJifYyt2RftAC-LugntNO70Zns8Nc',
    appId: '1:636277696280:android:cc79a1007baa596ba1206d',
    messagingSenderId: '636277696280',
    projectId: 'budgetmate-app-a94da',
    storageBucket: 'budgetmate-app-a94da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_bR-20sEJp6CpbU7Bgh9poAtBHnsMREQ',
    appId: '1:636277696280:ios:5c02afbb198561fca1206d',
    messagingSenderId: '636277696280',
    projectId: 'budgetmate-app-a94da',
    storageBucket: 'budgetmate-app-a94da.firebasestorage.app',
    iosClientId: '636277696280-uu3s353g6un9d3mov24m31j336fr0vio.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_bR-20sEJp6CpbU7Bgh9poAtBHnsMREQ',
    appId: '1:636277696280:ios:5c02afbb198561fca1206d',
    messagingSenderId: '636277696280',
    projectId: 'budgetmate-app-a94da',
    storageBucket: 'budgetmate-app-a94da.firebasestorage.app',
    iosClientId: '636277696280-uu3s353g6un9d3mov24m31j336fr0vio.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
