/// 3D clay illustrations, in persisted artwork-number order (136 onwards).
/// Images live in pastel_collection_00.png through pastel_collection_11.png.
/// Append only: saved categories refer to these positions.
const additionalCategoryArtwork = <(String, String, String)>[
  ('องุ่น', 'Grapes', 'food'),
  ('เมลอน', 'Melon', 'food'),
  ('แตงโม', 'Watermelon', 'food'),
  ('ส้ม', 'Orange', 'food'),
  ('เลมอน', 'Lemon', 'food'),
  ('กล้วย', 'Banana', 'food'),
  ('สับปะรด', 'Pineapple', 'food'),
  ('มะม่วง', 'Mango', 'food'),
  ('แอปเปิลแดง', 'Red apple', 'food'),
  ('ลูกแพร์', 'Pear', 'food'),
  ('ลูกพีช', 'Peach', 'food'),
  ('เชอร์รี', 'Cherries', 'food'),
  ('สตรอว์เบอร์รี', 'Strawberry', 'food'),
  ('บลูเบอร์รี', 'Blueberries', 'food'),
  ('กีวี', 'Kiwi', 'food'),
  ('มะเขือเทศ', 'Tomato', 'food'),
  ('มะกอก', 'Olives', 'food'),
  ('มะพร้าว', 'Coconut', 'food'),
  ('อะโวคาโด', 'Avocado', 'food'),
  ('มะเขือม่วง', 'Eggplant', 'food'),
  ('มันฝรั่ง', 'Potato', 'food'),
  ('แครอต', 'Carrot', 'food'),
  ('ข้าวโพด', 'Corn', 'food'),
  ('พริก', 'Chili', 'food'),
  ('พริกหวาน', 'Bell pepper', 'food'),
  ('แตงกวา', 'Cucumber', 'food'),
  ('ผักใบเขียว', 'Leafy greens', 'food'),
  ('บรอกโคลี', 'Broccoli', 'food'),
  ('กระเทียม', 'Garlic', 'food'),
  ('หัวหอม', 'Onion', 'food'),
  ('เห็ด', 'Mushroom', 'food'),
  ('ถั่วลิสง', 'Peanuts', 'food'),
  ('เกาลัด', 'Chestnut', 'food'),
  ('ขนมปัง', 'Bread', 'food'),
  ('บาแก็ต', 'Baguette', 'food'),
  ('ขนมปังแผ่น', 'Flatbread', 'food'),
  ('เพรตเซล', 'Pretzel', 'food'),
  ('เบเกิล', 'Bagel', 'food'),
  ('แพนเค้ก', 'Pancakes', 'food'),
  ('วาฟเฟิล', 'Waffle', 'food'),
  ('ชีส', 'Cheese', 'food'),
  ('เนื้อติดกระดูก', 'Meat on bone', 'food'),
  ('น่องไก่', 'Chicken leg', 'food'),
  ('สเต๊ก', 'Steak', 'food'),
  ('เบคอน', 'Bacon', 'food'),
  ('แฮมเบอร์เกอร์', 'Hamburger', 'food'),
  ('เฟรนช์ฟรายส์', 'French fries', 'food'),
  ('ฮอตดอก', 'Hot dog', 'food'),
  ('แซนด์วิช', 'Sandwich', 'food'),
  ('ทาโก้', 'Taco', 'food'),
  ('เบอร์ริโต', 'Burrito', 'food'),
  ('ทามาเล', 'Tamale', 'food'),
  ('พิตา', 'Stuffed pita', 'food'),
  ('ฟาลาเฟล', 'Falafel', 'food'),
  ('ไข่ไก่', 'Egg', 'food'),
  ('ไข่ดาว', 'Fried egg', 'food'),
  ('อาหารกระทะ', 'Paella', 'food'),
  ('สตูว์', 'Stew', 'food'),
  ('ฟองดู', 'Fondue', 'food'),
  ('ซีเรียล', 'Cereal', 'food'),
  ('สลัด', 'Salad', 'food'),
  ('ป๊อปคอร์น', 'Popcorn', 'food'),
  ('เนย', 'Butter', 'food'),
  ('เกลือ', 'Salt', 'food'),
  ('อาหารกระป๋อง', 'Canned food', 'food'),
  ('เบนโตะ', 'Bento', 'food'),
  ('ข้าวเกรียบ', 'Rice cracker', 'food'),
  ('ข้าวปั้น', 'Rice ball', 'food'),
  ('ข้าวสวย', 'Cooked rice', 'food'),
  ('ข้าวแกงกะหรี่', 'Curry rice', 'food'),
  ('ก๋วยเตี๋ยว', 'Noodles', 'food'),
  ('สปาเกตตี', 'Spaghetti', 'food'),
  ('มันเผา', 'Roasted sweet potato', 'food'),
  ('โอเด้ง', 'Oden', 'food'),
  ('กุ้งทอด', 'Fried shrimp', 'food'),
  ('ลูกชิ้นปลา', 'Fish cake', 'food'),
  ('ขนมไหว้พระจันทร์', 'Mooncake', 'food'),
  ('ดังโงะ', 'Dango', 'food'),
  ('เกี๊ยว', 'Dumpling', 'food'),
  ('คุกกี้เสี่ยงทาย', 'Fortune cookie', 'food'),
  ('อาหารกลับบ้าน', 'Takeout', 'food'),
  ('หอยนางรม', 'Oyster', 'food'),
  ('น้ำแข็งไส', 'Shaved ice', 'food'),
  ('พาย', 'Pie', 'food'),
  ('คัพเค้ก', 'Cupcake', 'food'),
  ('คุกกี้', 'Cookie', 'food'),
  ('ช็อกโกแลต', 'Chocolate', 'food'),
  ('ลูกอม', 'Candy', 'food'),
  ('อมยิ้ม', 'Lollipop', 'food'),
  ('คัสตาร์ด', 'Custard', 'food'),
  ('น้ำผึ้ง', 'Honey', 'food'),
  ('นมสด', 'Milk', 'food'),
  ('กาน้ำชา', 'Teapot', 'food'),
  ('ชาเขียว', 'Green tea', 'food'),
  ('สาเก', 'Sake', 'food'),
  ('แชมเปญ', 'Champagne', 'food'),
  ('ไวน์', 'Wine', 'food'),
  ('มาร์ตินี', 'Martini', 'food'),
  ('น้ำผลไม้ค็อกเทล', 'Tropical drink', 'food'),
  ('เบียร์', 'Beer', 'food'),
  ('วิสกี้', 'Whisky', 'food'),
  ('ชานมไข่มุก', 'Bubble tea', 'food'),
  ('น้ำผลไม้กล่อง', 'Juice box', 'food'),
  ('ชามาเต', 'Mate', 'food'),
  ('น้ำแข็ง', 'Ice cube', 'food'),
  ('ตะเกียบ', 'Chopsticks', 'food'),
  ('ช้อนส้อม', 'Cutlery', 'food'),
  ('ช้อน', 'Spoon', 'food'),
  ('มีดทำครัว', 'Kitchen knife', 'food'),
  ('โถดินเผา', 'Amphora', 'food'),
  ('คอมพิวเตอร์ตั้งโต๊ะ', 'Desktop computer', 'tech'),
  ('เมาส์', 'Mouse', 'tech'),
  ('แทร็กบอล', 'Trackball', 'tech'),
  ('จอยสติ๊ก', 'Joystick', 'tech'),
  ('มินิดิสก์', 'Minidisc', 'tech'),
  ('ฟลอปปีดิสก์', 'Floppy disk', 'tech'),
  ('แผ่นซีดี', 'Compact disc', 'tech'),
  ('วิดีโอเทป', 'Videotape', 'tech'),
  ('กล้องวิดีโอ', 'Video camera', 'tech'),
  ('เครื่องฉายภาพ', 'Film projector', 'tech'),
  ('โทรทัศน์', 'Television', 'tech'),
  ('วิทยุ', 'Radio', 'tech'),
  ('เพจเจอร์', 'Pager', 'tech'),
  ('แฟกซ์', 'Fax', 'tech'),
  ('โทรศัพท์บ้าน', 'Telephone', 'tech'),
  ('แบตเตอรี่', 'Battery', 'tech'),
  ('ปลั๊กไฟ', 'Electric plug', 'tech'),
  ('ดาวเทียม', 'Satellite', 'tech'),
  ('จานรับสัญญาณ', 'Satellite dish', 'tech'),
  ('ลูกคิด', 'Abacus', 'tech'),
  ('หลอดไฟ', 'Light bulb', 'tech'),
  ('ไฟฉาย', 'Flashlight', 'tech'),
  ('เทียน', 'Candle', 'tech'),
  ('กล้องจุลทรรศน์', 'Microscope', 'tech'),
  ('กล้องโทรทรรศน์', 'Telescope', 'tech'),
  ('เฟือง', 'Gear', 'tech'),
  ('แม่เหล็ก', 'Magnet', 'tech'),
  ('หุ่นยนต์', 'Robot', 'tech'),
  ('ดีเอ็นเอ', 'DNA', 'tech'),
  ('หลอดทดลอง', 'Test tube', 'tech'),
  ('จานเพาะเชื้อ', 'Petri dish', 'tech'),
  ('เครื่องกลั่น', 'Alembic', 'tech'),
  ('นาฬิกาจับเวลา', 'Stopwatch', 'tech'),
  ('รับสายมือถือ', 'Incoming call', 'tech'),
  ('กระดิ่งแจ้งเตือน', 'Notification bell', 'tech'),
  ('รถเมล์', 'Bus', 'travel'),
  ('รถรางไฟฟ้า', 'Trolleybus', 'travel'),
  ('รถแข่ง', 'Racing car', 'travel'),
  ('รถตำรวจ', 'Police car', 'travel'),
  ('รถพยาบาล', 'Ambulance', 'travel'),
  ('รถดับเพลิง', 'Fire engine', 'travel'),
  ('รถตู้', 'Minibus', 'travel'),
  ('รถกระบะ', 'Pickup truck', 'travel'),
  ('รถส่งของ', 'Delivery truck', 'travel'),
  ('รถบรรทุกพ่วง', 'Articulated truck', 'travel'),
  ('รถแทรกเตอร์', 'Tractor', 'travel'),
  ('มอเตอร์ไซค์', 'Motorcycle', 'travel'),
  ('รถเข็นผู้ป่วย', 'Wheelchair', 'travel'),
  ('รถเข็นไฟฟ้า', 'Motorized wheelchair', 'travel'),
  ('รถตุ๊กตุ๊ก', 'Auto rickshaw', 'travel'),
  ('กระเช้าลอยฟ้า', 'Cable car', 'travel'),
  ('รถไฟแขวน', 'Suspension railway', 'travel'),
  ('ตู้รถไฟ', 'Railway carriage', 'travel'),
  ('รถไฟความเร็วสูง', 'Bullet train', 'travel'),
  ('รถไฟใต้ดิน', 'Metro', 'travel'),
  ('รถจักรไอน้ำ', 'Steam locomotive', 'travel'),
  ('เฮลิคอปเตอร์', 'Helicopter', 'travel'),
  ('เครื่องบินเล็ก', 'Small airplane', 'travel'),
  ('ร่มชูชีพ', 'Parachute', 'travel'),
  ('จรวด', 'Rocket', 'travel'),
  ('จานบิน', 'Flying saucer', 'travel'),
  ('เรือใบ', 'Sailboat', 'travel'),
  ('เรือแคนู', 'Canoe', 'travel'),
  ('เรือเร็ว', 'Speedboat', 'travel'),
  ('เรือสำราญ', 'Cruise ship', 'travel'),
  ('เรือเฟอร์รี', 'Ferry', 'travel'),
  ('สมอเรือ', 'Anchor', 'travel'),
  ('ไฟจราจร', 'Traffic light', 'travel'),
  ('เขตก่อสร้าง', 'Construction barrier', 'travel'),
  ('แผนที่โลก', 'World map', 'travel'),
  ('เข็มทิศ', 'Compass', 'travel'),
  ('โมอาย', 'Moai statue', 'travel'),
  ('เทพีเสรีภาพ', 'Statue of Liberty', 'travel'),
  ('โตเกียวทาวเวอร์', 'Tokyo tower', 'travel'),
  ('ปราสาท', 'Castle', 'travel'),
  ('ปราสาทญี่ปุ่น', 'Japanese castle', 'travel'),
  ('สนามกีฬา', 'Stadium', 'travel'),
  ('ชิงช้าสวรรค์', 'Ferris wheel', 'travel'),
  ('รถไฟเหาะ', 'Roller coaster', 'travel'),
  ('ม้าหมุน', 'Carousel', 'travel'),
  ('น้ำพุ', 'Fountain', 'travel'),
  ('ภูเขา', 'Mountain', 'travel'),
  ('ภูเขาไฟ', 'Volcano', 'travel'),
  ('ทะเลทราย', 'Desert', 'travel'),
  ('เกาะ', 'Island', 'travel'),
  ('อุทยานแห่งชาติ', 'National park', 'travel'),
  ('พระอาทิตย์ขึ้น', 'Sunrise', 'travel'),
  ('สะพานยามค่ำ', 'Bridge at night', 'travel'),
  ('โบสถ์', 'Church', 'travel'),
  ('รางรถไฟ', 'Railway track', 'travel'),
  ('ทางด่วน', 'Motorway', 'travel'),
  ('โรงแรม', 'Hotel', 'travel'),
  ('พิพิธภัณฑ์', 'Museum', 'travel'),
  ('ประตูศาลเจ้า', 'Shrine gate', 'travel'),
  ('มัสยิด', 'Mosque', 'travel'),
  ('หมวกปีก', 'Sun hat', 'fashion'),
  ('หมวกทรงสูง', 'Top hat', 'fashion'),
  ('หมวกแก๊ป', 'Cap', 'fashion'),
  ('หมวกรับปริญญา', 'Graduation cap', 'fashion'),
  ('หมวกกู้ภัย', 'Rescue helmet', 'fashion'),
  ('มงกุฎ', 'Crown', 'fashion'),
  ('ชุดเดรส', 'Dress', 'fashion'),
  ('กิโมโน', 'Kimono', 'fashion'),
  ('ส่าหรี', 'Sari', 'fashion'),
  ('ชุดว่ายน้ำ', 'Swimsuit', 'fashion'),
  ('บิกินี', 'Bikini', 'fashion'),
  ('กางเกงขาสั้น', 'Shorts', 'fashion'),
  ('กางเกงยีนส์', 'Jeans', 'fashion'),
  ('เนกไท', 'Necktie', 'fashion'),
  ('เสื้อยืด', 'T-shirt', 'fashion'),
  ('เสื้อโค้ต', 'Coat', 'fashion'),
  ('เสื้อกาวน์', 'Lab coat', 'fashion'),
  ('เสื้อสะท้อนแสง', 'Safety vest', 'fashion'),
  ('ผ้าพันคอ', 'Scarf', 'fashion'),
  ('ถุงมือ', 'Gloves', 'fashion'),
  ('ถุงเท้า', 'Socks', 'fashion'),
  ('รองเท้าส้นสูง', 'High heels', 'fashion'),
  ('รองเท้าแตะผู้หญิง', 'Sandal', 'fashion'),
  ('รองเท้าแตะหนีบ', 'Flip-flop', 'fashion'),
  ('รองเท้าบูต', 'Boots', 'fashion'),
  ('รองเท้าบัลเลต์', 'Flat shoes', 'fashion'),
  ('รองเท้าเดินป่า', 'Hiking boots', 'fashion'),
  ('รองเท้าเต้นบัลเลต์', 'Pointe shoes', 'fashion'),
  ('รองเท้าหนัง', 'Dress shoes', 'fashion'),
  ('กระเป๋าสตางค์', 'Purse', 'fashion'),
  ('กระเป๋าคลัตช์', 'Clutch', 'fashion'),
  ('กระเป๋าเป้', 'Backpack', 'fashion'),
  ('เข็มกลัดซ่อนปลาย', 'Safety pin', 'fashion'),
  ('แว่นสายตา', 'Eyeglasses', 'fashion'),
  ('แว่นนิรภัย', 'Goggles', 'fashion'),
  ('อัญมณี', 'Gemstone', 'fashion'),
  ('โบผูกผม', 'Ribbon', 'fashion'),
  ('กระจก', 'Mirror', 'fashion'),
  ('มีดโกน', 'Razor', 'fashion'),
  ('ทำเล็บ', 'Nail polish', 'fashion'),
  ('อเมริกันฟุตบอล', 'American football', 'hobby'),
  ('เบสบอล', 'Baseball', 'hobby'),
  ('ซอฟต์บอล', 'Softball', 'hobby'),
  ('วอลเลย์บอล', 'Volleyball', 'hobby'),
  ('รักบี้', 'Rugby', 'hobby'),
  ('จานร่อน', 'Flying disc', 'hobby'),
  ('บิลเลียด', 'Billiards', 'hobby'),
  ('ปิงปอง', 'Table tennis', 'hobby'),
  ('แบดมินตัน', 'Badminton', 'hobby'),
  ('ฮอกกี้น้ำแข็ง', 'Ice hockey', 'hobby'),
  ('ฮอกกี้สนาม', 'Field hockey', 'hobby'),
  ('ลาครอส', 'Lacrosse', 'hobby'),
  ('คริกเก็ต', 'Cricket', 'hobby'),
  ('บูมเมอแรง', 'Boomerang', 'hobby'),
  ('ประตูฟุตบอล', 'Goal net', 'hobby'),
  ('กอล์ฟ', 'Golf', 'hobby'),
  ('ว่าว', 'Kite', 'hobby'),
  ('ธนู', 'Archery', 'hobby'),
  ('ตกปลา', 'Fishing', 'hobby'),
  ('ดำน้ำ', 'Diving mask', 'hobby'),
  ('นวมมวย', 'Boxing glove', 'hobby'),
  ('ชุดศิลปะต่อสู้', 'Martial arts uniform', 'hobby'),
  ('สเกตบอร์ด', 'Skateboard', 'hobby'),
  ('โรลเลอร์สเกต', 'Roller skate', 'hobby'),
  ('เลื่อนหิมะ', 'Sled', 'hobby'),
  ('สเกตน้ำแข็ง', 'Ice skate', 'hobby'),
  ('เคอร์ลิง', 'Curling', 'hobby'),
  ('สกี', 'Skis', 'hobby'),
  ('ปาเป้า', 'Darts', 'hobby'),
  ('โบว์ลิง', 'Bowling', 'hobby'),
  ('ลูกเต๋า', 'Dice', 'hobby'),
  ('หมากรุก', 'Chess', 'hobby'),
  ('โยโย่', 'Yo-yo', 'hobby'),
  ('ไม้กายสิทธิ์', 'Magic wand', 'hobby'),
  ('ละครเวที', 'Theater', 'hobby'),
  ('ด้าย', 'Thread', 'hobby'),
  ('เข็มเย็บผ้า', 'Sewing needle', 'hobby'),
  ('ไหมพรม', 'Yarn', 'hobby'),
  ('ปมเชือก', 'Knot', 'hobby'),
  ('แซกโซโฟน', 'Saxophone', 'hobby'),
  ('แอคคอร์เดียน', 'Accordion', 'hobby'),
  ('เปียโน', 'Piano', 'hobby'),
  ('ทรัมเป็ต', 'Trumpet', 'hobby'),
  ('ไวโอลิน', 'Violin', 'hobby'),
  ('แบนโจ', 'Banjo', 'hobby'),
  ('กลองชุด', 'Drum', 'hobby'),
  ('กลองยาว', 'Long drum', 'hobby'),
  ('โน้ตเพลง', 'Musical score', 'hobby'),
  ('บัตรเข้าชม', 'Admission ticket', 'hobby'),
  ('ละครสัตว์', 'Circus', 'hobby'),
  ('โยนบอลโชว์', 'Juggling', 'hobby'),
  ('เล่นเซิร์ฟ', 'Surfing', 'hobby'),
  ('ว่ายน้ำ', 'Swimming', 'hobby'),
  ('พายเรือ', 'Rowing', 'hobby'),
  ('ปีนหน้าผา', 'Climbing', 'hobby'),
  ('สุนัข', 'Dog', 'life'),
  ('แมว', 'Cat', 'life'),
  ('หนู', 'Mouse animal', 'life'),
  ('แฮมสเตอร์', 'Hamster', 'life'),
  ('กระต่าย', 'Rabbit', 'life'),
  ('สุนัขจิ้งจอก', 'Fox', 'life'),
  ('หมี', 'Bear', 'life'),
  ('แพนด้า', 'Panda', 'life'),
  ('โคอาลา', 'Koala', 'life'),
  ('เสือ', 'Tiger', 'life'),
  ('สิงโต', 'Lion', 'life'),
  ('วัว', 'Cow', 'life'),
  ('หมู', 'Pig', 'life'),
  ('กบ', 'Frog', 'life'),
  ('ลิง', 'Monkey', 'life'),
  ('ไก่', 'Chicken', 'life'),
  ('เพนกวิน', 'Penguin', 'life'),
  ('นก', 'Bird', 'life'),
  ('ลูกเจี๊ยบ', 'Chick', 'life'),
  ('เป็ด', 'Duck', 'life'),
  ('นกอินทรี', 'Eagle', 'life'),
  ('นกฮูก', 'Owl', 'life'),
  ('ค้างคาว', 'Bat', 'life'),
  ('หมาป่า', 'Wolf', 'life'),
  ('หมูป่า', 'Boar', 'life'),
  ('ม้า', 'Horse', 'life'),
  ('ยูนิคอร์น', 'Unicorn', 'life'),
  ('ผึ้ง', 'Bee', 'life'),
  ('หนอน', 'Caterpillar', 'life'),
  ('ผีเสื้อ', 'Butterfly', 'life'),
  ('หอยทาก', 'Snail', 'life'),
  ('เต่าทอง', 'Ladybug', 'life'),
  ('มด', 'Ant', 'life'),
  ('ยุง', 'Mosquito', 'life'),
  ('ด้วง', 'Beetle', 'life'),
  ('จิ้งหรีด', 'Cricket insect', 'life'),
  ('แมงมุม', 'Spider', 'life'),
  ('แมงป่อง', 'Scorpion', 'life'),
  ('เต่า', 'Turtle', 'life'),
  ('งู', 'Snake', 'life'),
  ('กิ้งก่า', 'Lizard', 'life'),
  ('ไดโนเสาร์ทีเร็กซ์', 'T-rex', 'life'),
  ('ไดโนเสาร์คอยาว', 'Sauropod', 'life'),
  ('ปลาหมึกยักษ์', 'Octopus', 'life'),
  ('ปลาหมึก', 'Squid', 'life'),
  ('กุ้ง', 'Shrimp', 'life'),
  ('กุ้งมังกร', 'Lobster', 'life'),
  ('ปู', 'Crab', 'life'),
  ('ปลาปักเป้า', 'Blowfish', 'life'),
  ('ปลาสวยงาม', 'Tropical fish', 'life'),
  ('ปลา', 'Fish', 'life'),
  ('โลมา', 'Dolphin', 'life'),
  ('วาฬ', 'Whale', 'life'),
  ('ฉลาม', 'Shark', 'life'),
  ('แมวน้ำ', 'Seal', 'life'),
  ('จระเข้', 'Crocodile', 'life'),
  ('ไก่งวง', 'Turkey', 'life'),
  ('เสือดาว', 'Leopard', 'life'),
  ('ม้าลาย', 'Zebra', 'life'),
  ('กอริลลา', 'Gorilla', 'life'),
  ('อุรังอุตัง', 'Orangutan', 'life'),
  ('แมมมอธ', 'Mammoth', 'life'),
  ('ช้าง', 'Elephant', 'life'),
  ('ฮิปโป', 'Hippopotamus', 'life'),
  ('แรด', 'Rhinoceros', 'life'),
  ('อูฐ', 'Camel', 'life'),
  ('ยีราฟ', 'Giraffe', 'life'),
  ('จิงโจ้', 'Kangaroo', 'life'),
  ('ไบซัน', 'Bison', 'life'),
  ('ควาย', 'Water buffalo', 'life'),
  ('วัวกระทิง', 'Ox', 'life'),
  ('แกะตัวผู้', 'Ram', 'life'),
  ('แกะ', 'Sheep', 'life'),
  ('ลามา', 'Llama', 'life'),
  ('แพะ', 'Goat', 'life'),
  ('กวาง', 'Deer', 'life'),
  ('นกยูง', 'Peacock', 'life'),
  ('นกแก้ว', 'Parrot', 'life'),
  ('หงส์', 'Swan', 'life'),
  ('ฟลามิงโก', 'Flamingo', 'life'),
  ('นกพิราบ', 'Dove', 'life'),
  ('แรคคูน', 'Raccoon', 'life'),
  ('สกังก์', 'Skunk', 'life'),
  ('แบดเจอร์', 'Badger', 'life'),
  ('บีเวอร์', 'Beaver', 'life'),
  ('นาก', 'Otter', 'life'),
  ('สลอธ', 'Sloth', 'life'),
  ('กระรอก', 'Squirrel', 'life'),
  ('เม่น', 'Hedgehog', 'life'),
  ('รอยเท้าสัตว์', 'Paw prints', 'life'),
  ('ต้นสน', 'Evergreen tree', 'life'),
  ('ต้นไม้ผลัดใบ', 'Deciduous tree', 'life'),
  ('ต้นปาล์ม', 'Palm tree', 'life'),
  ('ต้นกล้า', 'Seedling', 'life'),
  ('สมุนไพร', 'Herb', 'life'),
  ('แชมร็อก', 'Shamrock', 'life'),
  ('โคลเวอร์สี่แฉก', 'Four leaf clover', 'life'),
  ('ต้นไผ่ประดับ', 'Pine decoration', 'life'),
  ('ไม้กระถาง', 'Potted plant', 'life'),
  ('ต้นทานาบาตะ', 'Tanabata tree', 'life'),
  ('ใบไม้ปลิว', 'Leaf in wind', 'life'),
  ('ใบไม้ร่วง', 'Fallen leaf', 'life'),
  ('ใบเมเปิล', 'Maple leaf', 'life'),
  ('รวงข้าว', 'Sheaf of rice', 'life'),
  ('ชบา', 'Hibiscus', 'life'),
  ('ทานตะวัน', 'Sunflower', 'life'),
  ('กุหลาบ', 'Rose', 'life'),
  ('ทิวลิป', 'Tulip', 'life'),
  ('ซากุระ', 'Cherry blossom', 'life'),
  ('ดอกเดซี', 'Daisy', 'life'),
];
